import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { z } from 'zod';
import {
  applyLearningSchema,
  canonicalEvidenceFailure,
  canonicalJson,
  learningEvidenceRecordSchema,
  learningStorageBytes,
  LEARNING_LIMITS,
  LEARNING_SIGNALS,
  pruneLearning,
  sha256Hex,
  type LearningEvidenceRecord,
  type LearningSignal,
} from './workspace.js';

export type MessageRole = 'user' | 'assistant' | 'system' | 'tool';
/**
 * Who started a run, recorded by the server at admission and never read from
 * client metadata. `web_owner` is the only source that can seed learning.
 */
export type AdmittedRunSource =
  | 'web_owner'
  | 'channel_owner'
  | 'scheduled_task'
  | 'voice_compute'
  | 'voice_receipt';
/** Server-initiated turns that share the runner but are never owner web evidence. */
export type ServerTurnSource = Extract<
  AdmittedRunSource,
  'scheduled_task' | 'voice_compute' | 'voice_receipt'
>;
/** `unknown` marks runs recorded before provenance existed; they are never eligible. */
export type RunSource = AdmittedRunSource | 'unknown';
export interface ConversationMessage {
  id: string;
  threadId: string;
  dotId: string;
  ownerId: string;
  ordinal: number;
  role: MessageRole;
  content: unknown;
  toolCallId: string | null;
  toolResult: unknown;
  metadata: unknown;
  createdAt: number;
}
export type RunStatus = 'running' | 'completed' | 'failed' | 'interrupted';
export interface ConversationRun {
  id: string;
  threadId: string;
  status: RunStatus;
  startedAt: number;
  finishedAt: number | null;
  error: string | null;
  source: RunSource;
  /** Ordinals of the messages admitted or generated by this run; null when unrecorded. */
  firstOrdinal: number | null;
  lastOrdinal: number | null;
}
export interface LearningJobCandidate {
  signal: LearningSignal;
  evidence: LearningEvidenceRecord[];
  sourceDigest: string;
  /** Required for `repeated_workflow` and absent for every other signal. */
  patternHash?: string | null;
}
/** A canonical message with the digest of its stored content, which evidence records cite. */
export interface DigestedMessage {
  message: ConversationMessage;
  sha256: string;
}
export type LearningJobSkip =
  | 'run_not_completed'
  | 'invalid_candidate'
  | 'source_not_eligible'
  | 'unbounded_run'
  | 'unowned_thread'
  | 'not_enrolled'
  | 'dot_not_enabled'
  | 'duplicate_run'
  | 'evidence_unverified'
  | 'queue_full'
  | 'job_capacity'
  | 'storage_budget'
  | 'learning_unavailable';
export interface LearningJob {
  id: string;
  ownerId: string;
  dotId: string;
  threadId: string;
  sourceRunId: string;
  signal: LearningSignal;
  state:
    | 'queued'
    | 'running'
    | 'completed'
    | 'no_change'
    | 'failed'
    | 'interrupted'
    | 'cancelled';
  evidence: LearningEvidenceRecord[];
  sourceDigest: string;
  patternHash: string | null;
  consentRevision: number;
  lease: string | null;
  startedAt: number | null;
  finishedAt: number | null;
  reservedInputTokens: number;
  reservedOutputTokens: number;
  inputTokens: number | null;
  outputTokens: number | null;
  errorCode: string | null;
  createdAt: number;
}
/** The owner's current consent for one thread, read fresh from canonical bindings. */
export interface LearningConsent {
  ownerId: string;
  dotId: string;
  enrolled: boolean;
  learningEnabled: boolean;
  memoryAllowed: boolean;
}
/** Budget inputs for one claim. Every count is read inside the claiming transaction. */
export interface LearningClaimLimits {
  dayStart: number;
  dailyCalls: number;
  dailyTokens: number;
  dailyTimeoutMs: number;
  callTimeoutMs: number;
  dotDailyCalls: number;
  dotIntervalMs: number;
  reservedInputTokens: number;
  reservedOutputTokens: number;
}
export type LearningClaimSkip =
  | 'not_queued'
  | 'concurrent'
  | 'daily_calls'
  | 'daily_tokens'
  | 'daily_timeout'
  | 'dot_daily'
  | 'dot_interval';
export interface FinishedRun {
  run: ConversationRun;
  job: LearningJob | null;
  skipped: LearningJobSkip | null;
}
const learningJobCandidateSchema = z
  .object({
    signal: z.enum(LEARNING_SIGNALS),
    evidence: z
      .array(learningEvidenceRecordSchema)
      .min(1)
      .max(LEARNING_LIMITS.evidenceRecords),
    sourceDigest: z.string().regex(/^[0-9a-f]{64}$/),
    patternHash: z
      .string()
      .regex(/^[0-9a-f]{64}$/)
      .nullish(),
  })
  .strict();
export interface AgUiEvent {
  id: number;
  threadId: string;
  runId: string;
  seq: number;
  payload: unknown;
  createdAt: number;
}
export interface ConnectorInbound {
  id: number;
  platform: string;
  updateId: string;
  offset: number;
  createdAt: number;
}
export type OutboundStatus = 'pending' | 'attempting' | 'delivered' | 'failed';
export interface ConnectorOutbound {
  id: string;
  threadId: string;
  runId: string | null;
  status: OutboundStatus;
  retryCount: number;
  payload: unknown;
  error: string | null;
  createdAt: number;
  updatedAt: number;
}

function isUniqueViolation(error: unknown): boolean {
  return (
    error instanceof Error &&
    (error as NodeJS.ErrnoException).code === 'ERR_SQLITE_ERROR' &&
    /UNIQUE constraint failed/.test(error.message)
  );
}

type MessageRow = Omit<
  ConversationMessage,
  'content' | 'toolResult' | 'metadata'
> & {
  content: string;
  toolResult: string | null;
  metadata: string | null;
};
type EventRow = Omit<AgUiEvent, 'payload'> & { payload: string };
type OutboundRow = Omit<ConnectorOutbound, 'payload'> & { payload: string };
type LearningJobRow = Omit<LearningJob, 'evidence'> & { evidence: string };
function toLearningJob(row: LearningJobRow): LearningJob {
  return {
    ...row,
    evidence: JSON.parse(row.evidence) as LearningEvidenceRecord[],
  };
}

function toMessage(row: MessageRow): ConversationMessage {
  return {
    ...row,
    content: JSON.parse(row.content),
    toolResult: row.toolResult ? JSON.parse(row.toolResult) : null,
    metadata: row.metadata ? JSON.parse(row.metadata) : null,
  };
}
function toEvent(row: EventRow): AgUiEvent {
  return { ...row, payload: JSON.parse(row.payload) };
}
function toOutbound(row: OutboundRow): ConnectorOutbound {
  return { ...row, payload: JSON.parse(row.payload) };
}

// Sibling to Store (store.ts) and WorkspaceStore (workspace.ts): same WAL +
// BEGIN IMMEDIATE/COMMIT transaction pattern, kept independent so this
// transcript schema has no dependency on either.
export class ConversationStore {
  private db: DatabaseSync;
  constructor(path: string) {
    if (path !== ':memory:') mkdirSync(dirname(path), { recursive: true });
    this.db = new DatabaseSync(path);
    this.db
      .exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; PRAGMA foreign_keys=ON;
      CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY, threadId TEXT NOT NULL, dotId TEXT NOT NULL, ownerId TEXT NOT NULL, ordinal INTEGER NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL, toolCallId TEXT, toolResult TEXT, createdAt INTEGER NOT NULL, UNIQUE(threadId, ordinal));
      CREATE TABLE IF NOT EXISTS conversation_runs(id TEXT PRIMARY KEY, threadId TEXT NOT NULL, status TEXT NOT NULL, startedAt INTEGER NOT NULL, finishedAt INTEGER, error TEXT);
      CREATE TABLE IF NOT EXISTS ag_ui_events(id INTEGER PRIMARY KEY AUTOINCREMENT, threadId TEXT NOT NULL, runId TEXT NOT NULL, seq INTEGER NOT NULL, payload TEXT NOT NULL, createdAt INTEGER NOT NULL, UNIQUE(runId, seq));
      CREATE TABLE IF NOT EXISTS connector_inbound(id INTEGER PRIMARY KEY AUTOINCREMENT, platform TEXT NOT NULL, updateId TEXT NOT NULL, offset INTEGER NOT NULL, createdAt INTEGER NOT NULL, UNIQUE(platform, updateId));
      CREATE TABLE IF NOT EXISTS connector_outbound(id TEXT PRIMARY KEY, threadId TEXT NOT NULL, runId TEXT, status TEXT NOT NULL, payload TEXT NOT NULL, error TEXT, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL);
      CREATE INDEX IF NOT EXISTS conversation_runs_thread ON conversation_runs(threadId, startedAt);
      CREATE INDEX IF NOT EXISTS connector_inbound_offset ON connector_inbound(platform, offset);
      CREATE INDEX IF NOT EXISTS connector_outbound_status ON connector_outbound(threadId, status);`);
    // Additive forward compatibility: new columns arrive via ALTER TABLE ADD
    // COLUMN, never a destructive rewrite, mirroring workspace.ts's pattern.
    for (const [table, column, definition] of [
      ['messages', 'metadata', 'TEXT'],
      ['connector_outbound', 'retryCount', 'INTEGER NOT NULL DEFAULT 0'],
      // Legacy rows get 'unknown' and null bounds, so they are never eligible.
      ['conversation_runs', 'source', "TEXT NOT NULL DEFAULT 'unknown'"],
      ['conversation_runs', 'firstOrdinal', 'INTEGER NULL'],
      ['conversation_runs', 'lastOrdinal', 'INTEGER NULL'],
    ] as const) {
      if (
        !this.db
          .prepare(`PRAGMA table_info(${table})`)
          .all()
          .some((field) => field.name === column)
      )
        this.db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
    }
    applyLearningSchema(this.db);
  }
  close() {
    this.db.close();
  }
  private transaction<T>(fn: () => T): T {
    this.db.exec('BEGIN IMMEDIATE');
    try {
      const value = fn();
      this.db.exec('COMMIT');
      return value;
    } catch (error) {
      this.db.exec('ROLLBACK');
      throw error;
    }
  }
  private insertMessage(params: {
    threadId: string;
    dotId: string;
    ownerId: string;
    role: MessageRole;
    content: unknown;
    toolCallId?: string | null;
    toolResult?: unknown;
    metadata?: unknown;
  }): ConversationMessage {
    const next = this.db
      .prepare(
        'SELECT COALESCE(MAX(ordinal), -1) + 1 AS ordinal FROM messages WHERE threadId=?',
      )
      .get(params.threadId) as { ordinal: number };
    const message: ConversationMessage = {
      id: randomUUID(),
      threadId: params.threadId,
      dotId: params.dotId,
      ownerId: params.ownerId,
      ordinal: next.ordinal,
      role: params.role,
      content: params.content,
      toolCallId: params.toolCallId ?? null,
      toolResult: params.toolResult ?? null,
      metadata: params.metadata ?? null,
      createdAt: Date.now(),
    };
    this.db
      .prepare(
        'INSERT INTO messages (id, threadId, dotId, ownerId, ordinal, role, content, toolCallId, toolResult, createdAt, metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
      )
      .run(
        message.id,
        message.threadId,
        message.dotId,
        message.ownerId,
        message.ordinal,
        message.role,
        JSON.stringify(message.content),
        message.toolCallId,
        message.toolResult === null ? null : JSON.stringify(message.toolResult),
        message.createdAt,
        message.metadata === null ? null : JSON.stringify(message.metadata),
      );
    return message;
  }
  private insertRun(
    threadId: string,
    source: AdmittedRunSource,
    ordinal: number,
  ): ConversationRun {
    const run: ConversationRun = {
      id: randomUUID(),
      threadId,
      status: 'running',
      startedAt: Date.now(),
      finishedAt: null,
      error: null,
      source,
      firstOrdinal: ordinal,
      lastOrdinal: ordinal,
    };
    this.db
      .prepare(
        "INSERT INTO conversation_runs (id, threadId, status, startedAt, finishedAt, error, source, firstOrdinal, lastOrdinal) VALUES (?, ?, 'running', ?, NULL, NULL, ?, ?, ?)",
      )
      .run(
        run.id,
        run.threadId,
        run.startedAt,
        run.source,
        run.firstOrdinal,
        run.lastOrdinal,
      );
    return run;
  }
  /** Widens a run's recorded bounds to include an ordinal it just wrote. */
  private extendRunBounds(runId: string, ordinal: number) {
    this.db
      .prepare(
        'UPDATE conversation_runs SET firstOrdinal=COALESCE(firstOrdinal, ?), lastOrdinal=? WHERE id=?',
      )
      .run(ordinal, ordinal, runId);
  }
  private requireOpenRun(runId: string, threadId: string) {
    const run = this.run(runId);
    if (!run || run.threadId !== threadId)
      throw new Error('Run not found for this thread.');
    if (run.status !== 'running')
      throw new Error(
        `Run ${runId} cannot accept messages from status '${run.status}'.`,
      );
  }
  private insertEvent(
    threadId: string,
    runId: string,
    payload: unknown,
  ): AgUiEvent {
    const next = this.db
      .prepare(
        'SELECT COALESCE(MAX(seq), -1) + 1 AS seq FROM ag_ui_events WHERE runId=?',
      )
      .get(runId) as { seq: number };
    const createdAt = Date.now();
    const result = this.db
      .prepare(
        'INSERT INTO ag_ui_events (threadId, runId, seq, payload, createdAt) VALUES (?, ?, ?, ?, ?)',
      )
      .run(threadId, runId, next.seq, JSON.stringify(payload), createdAt);
    return {
      id: Number(result.lastInsertRowid),
      threadId,
      runId,
      seq: next.seq,
      payload,
      createdAt,
    };
  }
  // Admits one turn: the inbound message, its run, and the run-started event
  // all commit together, so no partially-committed turn is ever observable.
  admitTurn(params: {
    threadId: string;
    dotId: string;
    ownerId: string;
    role: MessageRole;
    content: unknown;
    toolCallId?: string | null;
    toolResult?: unknown;
    metadata?: unknown;
    source: AdmittedRunSource;
  }): { message: ConversationMessage; run: ConversationRun } {
    return this.transaction(() => {
      const message = this.insertMessage(params);
      const run = this.insertRun(
        params.threadId,
        params.source,
        message.ordinal,
      );
      this.insertEvent(run.threadId, run.id, {
        type: 'RUN_STARTED',
        messageId: message.id,
      });
      return { message, run };
    });
  }
  /**
   * Appends a message. With `runId`, the message must belong to a still-running
   * run on this thread, and it widens that run's recorded ordinal bounds in the
   * same transaction. A finished run cannot gain messages.
   */
  appendMessage(params: {
    threadId: string;
    dotId: string;
    ownerId: string;
    role: MessageRole;
    content: unknown;
    toolCallId?: string | null;
    toolResult?: unknown;
    metadata?: unknown;
    runId?: string;
  }): ConversationMessage {
    return this.transaction(() => {
      if (params.runId) this.requireOpenRun(params.runId, params.threadId);
      const message = this.insertMessage(params);
      if (params.runId) this.extendRunBounds(params.runId, message.ordinal);
      return message;
    });
  }
  messages(threadId: string): ConversationMessage[] {
    return (
      this.db
        .prepare('SELECT * FROM messages WHERE threadId=? ORDER BY ordinal')
        .all(threadId) as unknown as MessageRow[]
    ).map(toMessage);
  }
  run(id: string): ConversationRun | undefined {
    return this.db
      .prepare('SELECT * FROM conversation_runs WHERE id=?')
      .get(id) as unknown as ConversationRun | undefined;
  }
  runs(threadId: string): ConversationRun[] {
    return this.db
      .prepare(
        'SELECT * FROM conversation_runs WHERE threadId=? ORDER BY startedAt',
      )
      .all(threadId) as unknown as ConversationRun[];
  }
  finishRun(
    id: string,
    status: Exclude<RunStatus, 'running'>,
    error: string | null = null,
  ): ConversationRun {
    return this.finishRunWithLearning(id, status, error).run;
  }
  /**
   * Commits the terminal status and, in the same transaction, at most one
   * queued learning job. The job exists only if the run completed and every
   * eligibility rule holds. Its learning writes sit in a savepoint, so a
   * learning failure is reported as a skip and never rolls back the finished
   * chat turn. A crash before commit leaves neither the status nor the job.
   */
  finishRunWithLearning(
    id: string,
    status: Exclude<RunStatus, 'running'>,
    error: string | null = null,
    candidate: LearningJobCandidate | null = null,
  ): FinishedRun {
    return this.transaction(() => {
      const now = Date.now();
      const result = this.db
        .prepare(
          "UPDATE conversation_runs SET status=?, finishedAt=?, error=? WHERE id=? AND status='running'",
        )
        .run(status, now, error, id);
      if (Number(result.changes) === 0) {
        const existing = this.run(id);
        if (!existing) throw new Error('Run not found.');
        throw new Error(
          `Run ${id} cannot be finished from status '${existing.status}'.`,
        );
      }
      const run = this.run(id)!;
      this.insertEvent(run.threadId, run.id, {
        type: status === 'completed' ? 'RUN_FINISHED' : 'RUN_ERROR',
        error,
      });
      if (!candidate) return { run, job: null, skipped: null };
      return this.queueLearningJob(run, status, candidate);
    });
  }
  private queueLearningJob(
    run: ConversationRun,
    status: Exclude<RunStatus, 'running'>,
    candidate: LearningJobCandidate,
  ): FinishedRun {
    const skipped = (reason: LearningJobSkip): FinishedRun => ({
      run,
      job: null,
      skipped: reason,
    });
    if (status !== 'completed') return skipped('run_not_completed');
    const parsed = learningJobCandidateSchema.safeParse(candidate);
    if (!parsed.success) return skipped('invalid_candidate');
    // The pattern digest belongs to the repeated-workflow signal and no other.
    if (
      (parsed.data.signal === 'repeated_workflow') !==
      !!parsed.data.patternHash
    )
      return skipped('invalid_candidate');
    if (run.source !== 'web_owner') return skipped('source_not_eligible');
    if (run.firstOrdinal === null || run.lastOrdinal === null)
      return skipped('unbounded_run');
    this.db.exec('SAVEPOINT learning_job');
    try {
      const outcome = this.insertLearningJob(run, parsed.data);
      this.db.exec('RELEASE learning_job');
      return outcome;
    } catch {
      this.db.exec('ROLLBACK TO learning_job');
      this.db.exec('RELEASE learning_job');
      return skipped('learning_unavailable');
    }
  }
  private insertLearningJob(
    run: ConversationRun,
    candidate: z.infer<typeof learningJobCandidateSchema>,
  ): FinishedRun {
    const skipped = (reason: LearningJobSkip): FinishedRun => ({
      run,
      job: null,
      skipped: reason,
    });
    // The thread and Dot are read from canonical bindings, never from the caller.
    const thread = this.db
      .prepare(
        `SELECT tb.ownerId, tb.dotId, tb.localLearningEnrolled, d.learningEnabled,
                d.memoryAllowed, d.learningRevision
         FROM thread_bindings tb JOIN dots d ON d.id = tb.dotId
         WHERE tb.id = ?`,
      )
      .get(run.threadId) as
      | {
          ownerId: string;
          dotId: string;
          localLearningEnrolled: number;
          learningEnabled: number;
          memoryAllowed: number;
          learningRevision: number;
        }
      | undefined;
    if (!thread) return skipped('unowned_thread');
    if (!thread.localLearningEnrolled) return skipped('not_enrolled');
    if (!thread.learningEnabled || !thread.memoryAllowed)
      return skipped('dot_not_enabled');
    const existing = this.db
      .prepare('SELECT 1 FROM learning_jobs WHERE ownerId=? AND sourceRunId=?')
      .get(thread.ownerId, run.id);
    if (existing) return skipped('duplicate_run');
    const failure = canonicalEvidenceFailure(this.db, {
      dotId: thread.dotId,
      signal: candidate.signal,
      sourceRunId: run.id,
      evidence: candidate.evidence,
    });
    if (failure) return skipped('evidence_unverified');
    const evidence = canonicalJson(candidate.evidence);
    if (Buffer.byteLength(evidence, 'utf8') > LEARNING_LIMITS.evidenceBytes)
      return skipped('invalid_candidate');
    pruneLearning(this.db);
    const queued = this.db
      .prepare("SELECT COUNT(*) AS n FROM learning_jobs WHERE state='queued'")
      .get() as { n: number };
    if (Number(queued.n) >= LEARNING_LIMITS.queuedJobs)
      return skipped('queue_full');
    const jobs = this.db
      .prepare('SELECT COUNT(*) AS n FROM learning_jobs')
      .get() as { n: number };
    if (Number(jobs.n) >= LEARNING_LIMITS.jobRows)
      return skipped('job_capacity');
    if (
      learningStorageBytes(this.db) + Buffer.byteLength(evidence, 'utf8') >
      LEARNING_LIMITS.storageBytes
    )
      return skipped('storage_budget');
    const job: LearningJob = {
      id: randomUUID(),
      ownerId: thread.ownerId,
      dotId: thread.dotId,
      threadId: run.threadId,
      sourceRunId: run.id,
      signal: candidate.signal,
      state: 'queued',
      evidence: candidate.evidence,
      sourceDigest: candidate.sourceDigest,
      patternHash: candidate.patternHash ?? null,
      consentRevision: Number(thread.learningRevision),
      lease: null,
      startedAt: null,
      finishedAt: null,
      reservedInputTokens: 0,
      reservedOutputTokens: 0,
      inputTokens: null,
      outputTokens: null,
      errorCode: null,
      createdAt: Date.now(),
    };
    this.db
      .prepare(
        `INSERT INTO learning_jobs (id, ownerId, dotId, threadId, sourceRunId, signal, state, evidence, sourceDigest, patternHash, consentRevision, lease, startedAt, finishedAt, reservedInputTokens, reservedOutputTokens, inputTokens, outputTokens, errorCode, createdAt)
         VALUES (?, ?, ?, ?, ?, ?, 'queued', ?, ?, ?, ?, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, ?)`,
      )
      .run(
        job.id,
        job.ownerId,
        job.dotId,
        job.threadId,
        job.sourceRunId,
        job.signal,
        evidence,
        job.sourceDigest,
        job.patternHash,
        job.consentRevision,
        job.createdAt,
      );
    return { run, job, skipped: null };
  }
  learningJobs(): LearningJob[] {
    return (
      this.db
        .prepare('SELECT * FROM learning_jobs ORDER BY createdAt')
        .all() as unknown as LearningJobRow[]
    ).map(toLearningJob);
  }
  /** Queued learning jobs, oldest first. The extraction worker takes them one at a time. */
  learningJobsQueued(): LearningJob[] {
    return (
      this.db
        .prepare(
          "SELECT * FROM learning_jobs WHERE state='queued' ORDER BY createdAt, id",
        )
        .all() as unknown as LearningJobRow[]
    ).map(toLearningJob);
  }
  learningJob(id: string): LearningJob | undefined {
    const row = this.db
      .prepare('SELECT * FROM learning_jobs WHERE id=?')
      .get(id) as unknown as LearningJobRow | undefined;
    return row ? toLearningJob(row) : undefined;
  }
  /** The thread's owner, Dot, and consent flags as they stand now. */
  learningConsent(threadId: string): LearningConsent | undefined {
    const row = this.db
      .prepare(
        `SELECT tb.ownerId, tb.dotId, tb.localLearningEnrolled, d.learningEnabled, d.memoryAllowed
         FROM thread_bindings tb JOIN dots d ON d.id = tb.dotId
         WHERE tb.id = ?`,
      )
      .get(threadId) as
      | {
          ownerId: string;
          dotId: string;
          localLearningEnrolled: number;
          learningEnabled: number;
          memoryAllowed: number;
        }
      | undefined;
    if (!row) return undefined;
    return {
      ownerId: row.ownerId,
      dotId: row.dotId,
      enrolled: !!row.localLearningEnrolled,
      learningEnabled: !!row.learningEnabled,
      memoryAllowed: !!row.memoryAllowed,
    };
  }
  /** Canonical evidence check for a job's cited records; null when every record verifies. */
  learningEvidenceFailure(input: {
    dotId: string;
    sourceRunId: string;
    evidence: LearningEvidenceRecord[];
  }): string | null {
    return canonicalEvidenceFailure(this.db, input);
  }
  /** Canonical messages of one run's ordinal bounds, oldest first. */
  messagesBetween(
    threadId: string,
    firstOrdinal: number,
    lastOrdinal: number,
  ): ConversationMessage[] {
    return (
      this.db
        .prepare(
          'SELECT * FROM messages WHERE threadId=? AND ordinal BETWEEN ? AND ? ORDER BY ordinal',
        )
        .all(threadId, firstOrdinal, lastOrdinal) as unknown as MessageRow[]
    ).map(toMessage);
  }
  /**
   * Canonical messages of one run's ordinal bounds, restricted to `roles`, each
   * with the digest of its stored content. Signal detection reads only these.
   */
  boundedMessageDigests(
    threadId: string,
    firstOrdinal: number,
    lastOrdinal: number,
    roles: readonly MessageRole[],
  ): DigestedMessage[] {
    const placeholders = roles.map(() => '?').join(', ');
    return (
      this.db
        .prepare(
          `SELECT * FROM messages WHERE threadId=? AND ordinal BETWEEN ? AND ? AND role IN (${placeholders}) ORDER BY ordinal`,
        )
        .all(
          threadId,
          firstOrdinal,
          lastOrdinal,
          ...roles,
        ) as unknown as MessageRow[]
    ).map((row) => ({
      message: toMessage(row),
      sha256: sha256Hex(row.content),
    }));
  }
  /**
   * The most recent learning-eligible runs of one Dot, newest first: web-owner,
   * completed, bounded, on threads enrolled for local learning. `excludeRunId`
   * is the run being evaluated, which is never compared with itself.
   */
  learningRunsForDot(
    ownerId: string,
    dotId: string,
    since: number,
    limit: number,
    excludeRunId: string,
  ): ConversationRun[] {
    return this.db
      .prepare(
        `SELECT r.* FROM conversation_runs r JOIN thread_bindings tb ON tb.id = r.threadId
         WHERE tb.ownerId=? AND tb.dotId=? AND tb.localLearningEnrolled=1
           AND r.source='web_owner' AND r.status='completed'
           AND r.firstOrdinal IS NOT NULL AND r.lastOrdinal IS NOT NULL
           AND r.startedAt>=? AND r.id<>?
         ORDER BY r.startedAt DESC, r.rowid DESC LIMIT ?`,
      )
      .all(
        ownerId,
        dotId,
        since,
        excludeRunId,
        limit,
      ) as unknown as ConversationRun[];
  }
  /**
   * Moves one queued job to running under a new lease. The budget counts and the
   * single-running check happen in the same BEGIN IMMEDIATE transaction as the
   * update, so two claims cannot both pass a limit. A claim reserves its input
   * and output tokens; that reservation is never refunded.
   */
  claimLearningJob(
    id: string,
    lease: string,
    limits: LearningClaimLimits,
    now = Date.now(),
  ): { job: LearningJob } | { skipped: LearningClaimSkip } {
    return this.transaction<
      { job: LearningJob } | { skipped: LearningClaimSkip }
    >(() => {
      const job = this.learningJob(id);
      if (!job || job.state !== 'queued') return { skipped: 'not_queued' };
      const running = this.db
        .prepare(
          "SELECT COUNT(*) AS n FROM learning_jobs WHERE ownerId=? AND state='running'",
        )
        .get(job.ownerId) as { n: number };
      if (Number(running.n) > 0) return { skipped: 'concurrent' };
      const day = this.db
        .prepare(
          'SELECT COUNT(*) AS n, COALESCE(SUM(reservedInputTokens + reservedOutputTokens), 0) AS tokens FROM learning_jobs WHERE ownerId=? AND startedAt >= ?',
        )
        .get(job.ownerId, limits.dayStart) as { n: number; tokens: number };
      const calls = Number(day.n);
      if (calls + 1 > limits.dailyCalls) return { skipped: 'daily_calls' };
      const reserved = limits.reservedInputTokens + limits.reservedOutputTokens;
      if (Number(day.tokens) + reserved > limits.dailyTokens)
        return { skipped: 'daily_tokens' };
      if ((calls + 1) * limits.callTimeoutMs > limits.dailyTimeoutMs)
        return { skipped: 'daily_timeout' };
      const dot = this.db
        .prepare(
          'SELECT COUNT(*) AS n FROM learning_jobs WHERE ownerId=? AND dotId=? AND startedAt >= ?',
        )
        .get(job.ownerId, job.dotId, limits.dayStart) as { n: number };
      if (Number(dot.n) + 1 > limits.dotDailyCalls)
        return { skipped: 'dot_daily' };
      const recent = this.db
        .prepare(
          'SELECT 1 FROM learning_jobs WHERE ownerId=? AND dotId=? AND startedAt > ? LIMIT 1',
        )
        .get(job.ownerId, job.dotId, now - limits.dotIntervalMs);
      if (recent) return { skipped: 'dot_interval' };
      this.db
        .prepare(
          "UPDATE learning_jobs SET state='running', lease=?, startedAt=?, reservedInputTokens=?, reservedOutputTokens=? WHERE id=? AND state='queued'",
        )
        .run(
          lease,
          now,
          limits.reservedInputTokens,
          limits.reservedOutputTokens,
          id,
        );
      return { job: this.learningJob(id)! };
    });
  }
  /**
   * Commits a running job's outcome only while its lease is still current. A
   * stale or superseded lease changes nothing and returns false.
   */
  finishLearningJob(
    id: string,
    lease: string,
    outcome: {
      state: Extract<
        LearningJob['state'],
        'completed' | 'no_change' | 'failed' | 'interrupted' | 'cancelled'
      >;
      errorCode: string | null;
      inputTokens: number | null;
      outputTokens: number | null;
    },
    now = Date.now(),
  ): boolean {
    return this.transaction(() => {
      const result = this.db
        .prepare(
          "UPDATE learning_jobs SET state=?, finishedAt=?, errorCode=?, inputTokens=?, outputTokens=? WHERE id=? AND lease=? AND state='running'",
        )
        .run(
          outcome.state,
          now,
          outcome.errorCode,
          outcome.inputTokens,
          outcome.outputTokens,
          id,
          lease,
        );
      return Number(result.changes) === 1;
    });
  }
  /** Whether this lease still owns the running job. */
  learningLeaseHeld(id: string, lease: string): boolean {
    return !!this.db
      .prepare(
        "SELECT 1 FROM learning_jobs WHERE id=? AND lease=? AND state='running'",
      )
      .get(id, lease);
  }
  /** Cancels a job that has not started. A running job ends through finishLearningJob. */
  cancelLearningJob(id: string, errorCode: string, now = Date.now()): boolean {
    return this.transaction(() => {
      const result = this.db
        .prepare(
          "UPDATE learning_jobs SET state='cancelled', finishedAt=?, errorCode=? WHERE id=? AND state='queued'",
        )
        .run(now, errorCode, id);
      return Number(result.changes) === 1;
    });
  }
  /**
   * Startup recovery: a job still running belonged to a process that exited.
   * It becomes interrupted and is never repeated, so no paid call runs twice.
   */
  interruptRunningLearningJobs(now = Date.now()): number {
    return this.transaction(() => {
      const result = this.db
        .prepare(
          "UPDATE learning_jobs SET state='interrupted', finishedAt=?, errorCode='restart' WHERE state='running'",
        )
        .run(now);
      return Number(result.changes);
    });
  }
  recordEvent(threadId: string, runId: string, payload: unknown): AgUiEvent {
    return this.transaction(() => this.insertEvent(threadId, runId, payload));
  }
  events(runId: string): AgUiEvent[] {
    return (
      this.db
        .prepare('SELECT * FROM ag_ui_events WHERE runId=? ORDER BY seq')
        .all(runId) as unknown as EventRow[]
    ).map(toEvent);
  }
  admitInboundTurn(params: {
    platform: string;
    updateId: string;
    offset: number;
    threadId: string;
    dotId: string;
    ownerId: string;
    role: MessageRole;
    content: unknown;
    metadata?: unknown;
    source: AdmittedRunSource;
  }): { message: ConversationMessage; run: ConversationRun } | null {
    return this.transaction(() => {
      try {
        this.db
          .prepare(
            'INSERT INTO connector_inbound (platform, updateId, offset, createdAt) VALUES (?, ?, ?, ?)',
          )
          .run(params.platform, params.updateId, params.offset, Date.now());
      } catch (error) {
        if (isUniqueViolation(error)) return null;
        throw error;
      }
      const message = this.insertMessage(params);
      const run = this.insertRun(
        params.threadId,
        params.source,
        message.ordinal,
      );
      this.insertEvent(run.threadId, run.id, {
        type: 'RUN_STARTED',
        messageId: message.id,
      });
      return { message, run };
    });
  }
  // Durable dedup for redelivered platform updates: the (platform, updateId)
  // uniqueness constraint rejects the duplicate, not an application-level check.
  admitInbound(platform: string, updateId: string, offset: number): boolean {
    try {
      this.db
        .prepare(
          'INSERT INTO connector_inbound (platform, updateId, offset, createdAt) VALUES (?, ?, ?, ?)',
        )
        .run(platform, updateId, offset, Date.now());
      return true;
    } catch (error) {
      if (isUniqueViolation(error)) return false;
      throw error;
    }
  }
  highWaterOffset(platform: string): number | null {
    const row = this.db
      .prepare(
        'SELECT MAX(offset) AS offset FROM connector_inbound WHERE platform=?',
      )
      .get(platform) as { offset: number | null };
    return row.offset;
  }
  queueOutbound(
    threadId: string,
    runId: string | null,
    payload: unknown,
  ): ConnectorOutbound {
    const now = Date.now();
    const outbound: ConnectorOutbound = {
      id: randomUUID(),
      threadId,
      runId,
      status: 'pending',
      retryCount: 0,
      payload,
      error: null,
      createdAt: now,
      updatedAt: now,
    };
    this.db
      .prepare(
        "INSERT INTO connector_outbound (id, threadId, runId, status, payload, error, createdAt, updatedAt, retryCount) VALUES (?, ?, ?, 'pending', ?, NULL, ?, ?, 0)",
      )
      .run(outbound.id, threadId, runId, JSON.stringify(payload), now, now);
    return outbound;
  }
  outbound(id: string): ConnectorOutbound | undefined {
    const row = this.db
      .prepare('SELECT * FROM connector_outbound WHERE id=?')
      .get(id) as OutboundRow | undefined;
    return row ? toOutbound(row) : undefined;
  }
  pendingOutbound(threadId?: string): ConnectorOutbound[] {
    return (
      this.db
        .prepare(
          `SELECT * FROM connector_outbound WHERE status IN ('pending', 'attempting') ${threadId ? 'AND threadId=?' : ''} ORDER BY createdAt`,
        )
        .all(...(threadId ? [threadId] : [])) as unknown as OutboundRow[]
    ).map(toOutbound);
  }
  markOutbound(
    id: string,
    status: OutboundStatus,
    error: string | null = null,
  ): ConnectorOutbound {
    return this.transaction(() => {
      const current = this.outbound(id);
      if (!current) throw new Error('Outbound delivery not found.');
      const retryCount =
        status === 'failed' ? current.retryCount + 1 : current.retryCount;
      this.db
        .prepare(
          'UPDATE connector_outbound SET status=?, error=?, retryCount=?, updatedAt=? WHERE id=?',
        )
        .run(status, error, retryCount, Date.now(), id);
      return this.outbound(id)!;
    });
  }
}
